name: build-pyopencl-windows

on:
  workflow_dispatch:  # run manually
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install build dependencies
      run: |
        python -m pip install -U pip setuptools wheel pybind11

    - name: Build wheel with OpenGL interop
      env:
        CL: "/DCL_ENABLE_GL=1"
      run: |
        pip wheel . -w dist

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyopencl-windows
        path: dist/*.whl
