name: build-pyopencl-windows
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install build dependencies
        run: |
          python -m pip install -U pip setuptools wheel pybind11
      - name: Install OpenCL (Khronos SDK via vcpkg)
        run: >
          git clone https://github.com/microsoft/vcpkg.git

          .\vcpkg\bootstrap-vcpkg.bat

          .\vcpkg\vcpkg install opencl:x64-windows

          echo "VCPKG_ROOT=$PWD/vcpkg" | Out-File -FilePath $env:GITHUB_ENV
          -Encoding utf8 -Append

          echo
          "CMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake" |
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Build wheel with OpenGL interop
        env:
          CL: /PYOPENCL_ENABLE_GL=ON
          CMAKE_TOOLCHAIN_FILE: '${{ env.CMAKE_TOOLCHAIN_FILE }}'
        run: |
          pip wheel . -w dist
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyopencl-windows
          path: dist/*.whl
